.PHONY: clean All

All:
	@echo "----------Building project:[ raspiMain - Debug ]----------"
	@cd "raspiMain" && $(MAKE) -f  "raspiMain.mk"
clean:
	@echo "----------Cleaning project:[ raspiMain - Debug ]----------"
	@cd "raspiMain" && $(MAKE) -f  "raspiMain.mk" clean
